#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgweather
Version  : 4.0.0
Release  : 26
URL      : https://download.gnome.org/sources/libgweather/4.0/libgweather-4.0.0.tar.xz
Source0  : https://download.gnome.org/sources/libgweather/4.0/libgweather-4.0.0.tar.xz
Summary  : GObject-Introspection based documentation generator
Group    : Development/Tools
License  : Apache-2.0 CC-BY-SA-3.0 CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 MIT MPL-1.1 OFL-1.1
Requires: libgweather-data = %{version}-%{release}
Requires: libgweather-lib = %{version}-%{release}
Requires: libgweather-license = %{version}-%{release}
Requires: libgweather-locales = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gi-docgen
BuildRequires : gobject-introspection-dev
BuildRequires : pkgconfig(geocode-glib-1.0)
BuildRequires : pkgconfig(gi-docgen)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pygobject
BuildRequires : pypi(jinja2)
BuildRequires : pypi(markdown)
BuildRequires : pypi(markupsafe)
BuildRequires : pypi(pygments)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(toml)
BuildRequires : pypi(typogrify)
BuildRequires : pypi(wheel)
BuildRequires : tzdata
Patch1: backport-nodocs.patch

%description
[![Build Status](https://gitlab.gnome.org/GNOME/libgweather/badges/master/build.svg)](https://gitlab.gnome.org/GNOME/libgweather/pipelines)

%package data
Summary: data components for the libgweather package.
Group: Data

%description data
data components for the libgweather package.


%package dev
Summary: dev components for the libgweather package.
Group: Development
Requires: libgweather-lib = %{version}-%{release}
Requires: libgweather-data = %{version}-%{release}
Provides: libgweather-devel = %{version}-%{release}
Requires: libgweather = %{version}-%{release}

%description dev
dev components for the libgweather package.


%package lib
Summary: lib components for the libgweather package.
Group: Libraries
Requires: libgweather-data = %{version}-%{release}
Requires: libgweather-license = %{version}-%{release}

%description lib
lib components for the libgweather package.


%package license
Summary: license components for the libgweather package.
Group: Default

%description license
license components for the libgweather package.


%package locales
Summary: locales components for the libgweather package.
Group: Default

%description locales
locales components for the libgweather package.


%prep
%setup -q -n libgweather-4.0.0
cd %{_builddir}/libgweather-4.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647884919
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libgweather
cp %{_builddir}/libgweather-4.0.0/COPYING %{buildroot}/usr/share/package-licenses/libgweather/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/Apache-2.0.txt %{buildroot}/usr/share/package-licenses/libgweather/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/CC-BY-SA-3.0.txt %{buildroot}/usr/share/package-licenses/libgweather/fb41626a3005c2b6e14b8b3f5d9d0b19b5faaa51
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/libgweather/8287b608d3fa40ef401339fd907ca1260c964123
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/libgweather/3cb34cfc72e87654683f2894299adf912d14b284
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/libgweather/31a3d460bb3c7d98845187c716a30db81c44b615
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/libgweather/5c6c38fa1b6ac7c66252c83d1203e997ae3d1c98
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/libgweather/220906dfcc3d3b7f4e18cf8a22454c628ca0ea2e
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/MPL-1.1.txt %{buildroot}/usr/share/package-licenses/libgweather/ca2fd1439eb3e23507f13855e5450c5d617db83d
cp %{_builddir}/libgweather-4.0.0/subprojects/gi-docgen/LICENSES/OFL-1.1.txt %{buildroot}/usr/share/package-licenses/libgweather/8b8a351a8476e37a2c4d398eb1e6c8403f487ea4
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libgweather-4.0
%find_lang libgweather-4.0-locations

%files
%defattr(-,root,root,-)
/usr/lib64/libgweather-4/Locations.bin

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GWeather-4.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.GWeather4.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.GWeather4.gschema.xml
/usr/share/libgweather-4/Locations.xml
/usr/share/libgweather-4/locations.dtd
/usr/share/vala/vapi/gweather4.deps
/usr/share/vala/vapi/gweather4.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libgweather-4.0/libgweather/gweather-enum-types.h
/usr/include/libgweather-4.0/libgweather/gweather-enums.h
/usr/include/libgweather-4.0/libgweather/gweather-info.h
/usr/include/libgweather-4.0/libgweather/gweather-location.h
/usr/include/libgweather-4.0/libgweather/gweather-version.h
/usr/include/libgweather-4.0/libgweather/gweather.h
/usr/lib64/libgweather-4.so
/usr/lib64/pkgconfig/gweather4.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgweather-4.so.0
/usr/lib64/libgweather-4.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgweather/220906dfcc3d3b7f4e18cf8a22454c628ca0ea2e
/usr/share/package-licenses/libgweather/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/libgweather/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/libgweather/3cb34cfc72e87654683f2894299adf912d14b284
/usr/share/package-licenses/libgweather/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/libgweather/5c6c38fa1b6ac7c66252c83d1203e997ae3d1c98
/usr/share/package-licenses/libgweather/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/libgweather/8b8a351a8476e37a2c4d398eb1e6c8403f487ea4
/usr/share/package-licenses/libgweather/ca2fd1439eb3e23507f13855e5450c5d617db83d
/usr/share/package-licenses/libgweather/fb41626a3005c2b6e14b8b3f5d9d0b19b5faaa51

%files locales -f libgweather-4.0.lang -f libgweather-4.0-locations.lang
%defattr(-,root,root,-)

